apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redislb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redislb
  template:
    metadata:
      labels:
        app: redislb
    spec:
      volumes: 
      - name: vol
        persistentVolumeClaim:
          claimName: redisclaim
      containers:
      - name: redis
        image: redis:latest
        args: ["--requirepass","$(REDIS_PWD)"]
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redissecret
              key: password
        ports:
          - containerPort: 6379
        volumeMounts:
        - name: vol
          mountPath: "/data"
        
