apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp
  labels:
    app: voteapplb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapplb
  template:
    metadata:
      labels:
        app: voteapplb
    spec:
      containers:
      - name: voteapp
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        env:
          - name: STRESS_SECS
            value: "2"
          - name: REDIS
            value: "redis"
          - name: REDIS_PWD
            valueFrom:
              secretKeyRef:
                name: redissecret
                key: password
        ports:
          - containerPort: 80

