apiVersion: v1
kind: Service
metadata:
  name: clustredis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redislb

---
apiVersion: v1
kind: Service
metadata:
  name: clustvoteapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: voteapplb
